### ISSUE TITLE
Maj gestion du masquage

### ISSUE THREAD

**Issue by marc-bouvier** [marc-bouvier/form-anime-forum#15]
Gestion du masquage en fonction du service de simulcast (`<adn></adn> / <waka></waka> / <crunch></crunch> / <netflix></netflix> / <amazon></amazon>`) a ajouter après et avant [hide] / [/hide]

**Comment by Fu2chN** [comment]
Ça marche bien la tu veux faire quoi de plus ?

**Comment by marc-bouvier** [comment]
Je l'aiu vu dans les todo. C'était pour être sûr qu'il n'y ait rien d'autre a faire.
